apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 665751286595.dkr.ecr.ap-northeast-2.amazonaws.com/nginx-repo
  newName: 665751286595.dkr.ecr.ap-northeast-2.amazonaws.com/nginx-repo
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- nginx-deployment-patch.yaml
- nginx-service-patch.yaml
